# Generated by Django 4.2.1 on 2024-05-17 21:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('KnewITPeople', '0013_alter_person_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('website', models.CharField(default=None, max_length=128)),
                ('photo', models.FileField(blank=True, default=None, null=True, upload_to='photo/companies/')),
                ('place', models.TextField(default=None)),
                ('description', models.TextField(default=None)),
                ('workers_count', models.IntegerField(default=1)),
                ('activity_areas', models.TextField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('stack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='KnewITPeople.tech')),
            ],
        ),
    ]
