# Generated by Django 4.2.1 on 2024-05-17 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='frame',
            field=models.CharField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='payment',
            field=models.CharField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='requirements',
            field=models.TextField(default=None),
        ),
    ]
