# Generated by Django 4.2.1 on 2024-05-25 11:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0003_vacancy_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='vacancies_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='additionally',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='busyness',
            field=models.CharField(default='None'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='count_views',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='duties',
            field=models.TextField(default=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vacancy',
            name='experience',
            field=models.CharField(default='Without'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='offers',
            field=models.TextField(default=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vacancy',
            name='skills',
            field=models.CharField(default=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vacancy',
            name='title_desc',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='website',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
