# Generated by Django 4.2.1 on 2024-05-30 20:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('KnewITPeople', '0017_rename_frame_claim_work_stack_frame_and_more'),
        ('vacancies', '0004_company_vacancies_count_vacancy_additionally_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vacancy',
            name='frame',
        ),
        migrations.RemoveField(
            model_name='vacancy',
            name='stack',
        ),
        migrations.AddField(
            model_name='vacancy',
            name='stack_frame',
            field=models.ManyToManyField(related_name='vacancy_frame', to='KnewITPeople.tech'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date'),
        ),
    ]
