# Generated by Django 4.2.1 on 2023-12-14 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KnewITPeople', '0004_alter_certificates_file_alter_tech_frame'),
    ]

    operations = [
        migrations.RenameField(
            model_name='certificates',
            old_name='file',
            new_name='image',
        ),
        migrations.AlterField(
            model_name='person',
            name='photo',
            field=models.BinaryField(),
        ),
    ]
