# Generated by Django 4.2.1 on 2024-02-01 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KnewITPeople', '0010_remove_person_resume_remove_person_skills_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='photo',
            field=models.FileField(blank=True, default=None, null=True, upload_to='photo/'),
        ),
        migrations.AlterField(
            model_name='person',
            name='work_ex',
            field=models.TextField(blank=True, default=None),
        ),
    ]
