# Generated by Django 4.2.1 on 2024-02-01 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KnewITPeople', '0011_alter_person_photo_alter_person_work_ex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='work_ex',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
