# Generated by Django 4.2.1 on 2024-05-17 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KnewITPeople', '0012_alter_person_work_ex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='photo',
            field=models.FileField(blank=True, default=None, null=True, upload_to='photo/jobseekers/'),
        ),
    ]
