# Generated by Django 4.2.1 on 2024-05-28 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KnewITPeople', '0013_alter_person_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='claim_work',
            name='frame',
        ),
        migrations.RemoveField(
            model_name='claim_work',
            name='stack',
        ),
        migrations.AddField(
            model_name='claim_work',
            name='frame',
            field=models.ManyToManyField(related_name='claim_works_frame', to='KnewITPeople.tech'),
        ),
        migrations.AddField(
            model_name='claim_work',
            name='stack',
            field=models.ManyToManyField(related_name='claim_works_stack', to='KnewITPeople.tech'),
        ),
    ]
