# Generated by Django 4.2.1 on 2024-05-28 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KnewITPeople', '0015_remove_claim_work_stack_claim_work_stack'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claim_work',
            name='stack',
            field=models.CharField(max_length=128),
        ),
    ]
