# Generated by Django 4.2.1 on 2024-05-28 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('KnewITPeople', '0016_alter_claim_work_stack'),
    ]

    operations = [
        migrations.RenameField(
            model_name='claim_work',
            old_name='frame',
            new_name='stack_frame',
        ),
        migrations.RenameField(
            model_name='claim_work',
            old_name='stack',
            new_name='title',
        ),
    ]
