# Generated by Django 4.2.1 on 2024-05-30 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KnewITPeople', '0017_rename_frame_claim_work_stack_frame_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tech',
            name='frame',
            field=models.TextField(default=None, null=True),
        ),
    ]
