# Generated by Django 4.2.1 on 2024-05-30 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KnewITPeople', '0018_alter_tech_frame'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tech',
            name='frame',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
