# Generated by Django 4.2.1 on 2024-06-03 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('KnewITPeople', '0018_company_alter_tech_frame_vacancy'),
        ('KnewITPeople', '0019_alter_tech_frame'),
    ]

    operations = [
    ]
