# Generated by Django 4.2.1 on 2024-06-03 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KnewITPeople', '0020_merge_20240603_2213'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificates',
            name='person',
        ),
        migrations.AddField(
            model_name='person',
            name='certificates',
            field=models.ManyToManyField(related_name='certificates_person', to='KnewITPeople.certificates'),
        ),
        migrations.AlterField(
            model_name='tech',
            name='frame',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
