# Generated by Django 4.2.1 on 2024-06-03 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KnewITPeople', '0021_remove_certificates_person_person_certificates_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificates',
            name='person_name',
            field=models.CharField(default='Unknown', max_length=128),
        ),
    ]
