# Generated by Django 4.2.1 on 2024-06-03 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KnewITPeople', '0022_certificates_person_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='soc_links',
            name='twitter',
        ),
        migrations.AddField(
            model_name='soc_links',
            name='linkedIn',
            field=models.TextField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='soc_links',
            name='Github',
            field=models.TextField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='soc_links',
            name='WPP',
            field=models.TextField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='soc_links',
            name='instagram',
            field=models.TextField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='soc_links',
            name='resume',
            field=models.FileField(blank=True, default=None, upload_to='resume/'),
        ),
    ]
