# Generated by Django 4.2.1 on 2024-06-03 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KnewITPeople', '0023_remove_soc_links_twitter_soc_links_linkedin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soc_links',
            name='linkedIn',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
