# Generated by Django 4.2.1 on 2024-06-03 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KnewITPeople', '0025_tech_click_counter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='claim_work',
            name='desired_salary',
        ),
        migrations.AddField(
            model_name='person',
            name='personal_qualities',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
