# Generated by Django 4.2.1 on 2024-06-04 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KnewITPeople', '0026_remove_claim_work_desired_salary_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='certificates',
            field=models.ManyToManyField(blank=True, related_name='certificates_person', to='KnewITPeople.certificates'),
        ),
    ]
