# Generated by Django 4.2.1 on 2024-06-04 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('KnewITPeople', '0027_alter_person_certificates'),
    ]

    operations = [
        migrations.RenameField(
            model_name='soc_links',
            old_name='instagram',
            new_name='telegram',
        ),
    ]
