# Generated by Django 4.2.1 on 2024-06-04 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KnewITPeople', '0028_rename_instagram_soc_links_telegram'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='busyness',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='experience',
            field=models.CharField(default='Без опыта'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='payment',
            field=models.CharField(blank=True, default='Уровень дохода не указан', null=True),
        ),
    ]
