# Generated by Django 4.2.1 on 2024-06-04 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('KnewITPeople', '0029_alter_vacancy_busyness_alter_vacancy_experience_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vacancy',
            name='skills',
        ),
    ]
