# Generated by Django 4.2.1 on 2024-06-05 10:34

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('KnewITPeople', '0032_alter_person_company_employee'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='description',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='company',
            old_name='photo',
            new_name='logo_dark',
        ),
        migrations.RemoveField(
            model_name='company',
            name='activity_areas',
        ),
        migrations.RemoveField(
            model_name='company',
            name='vacancies_count',
        ),
        migrations.RemoveField(
            model_name='company',
            name='workers_count',
        ),
        migrations.AddField(
            model_name='company',
            name='full_name',
            field=models.CharField(default=12345, max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company',
            name='iin',
            field=models.CharField(default=123, max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company',
            name='logo_light',
            field=models.FileField(blank=True, default=None, null=True, upload_to='photo/companies/'),
        ),
        migrations.AddField(
            model_name='company',
            name='main_color_hex',
            field=models.CharField(default='#FFFFFF', max_length=7, validators=[django.core.validators.MinLengthValidator(7)]),
        ),
        migrations.AddField(
            model_name='company',
            name='phone',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company',
            name='secondary_color_hex',
            field=models.CharField(default='#FFFFFF', max_length=7, validators=[django.core.validators.MinLengthValidator(7)]),
        ),
        migrations.AddField(
            model_name='person',
            name='company',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='KnewITPeople.company'),
        ),
        migrations.AddField(
            model_name='tech',
            name='company',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='KnewITPeople.company'),
        ),
    ]
