# Generated by Django 4.2.1 on 2024-06-04 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KnewITPeople', '0032_alter_person_company_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='company_employee',
            field=models.CharField(blank=True, default=None),
        ),
    ]
