# Generated by Django 4.2.1 on 2024-06-05 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KnewITPeople', '0033_rename_description_company_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='website',
            field=models.CharField(default=1, max_length=128),
            preserve_default=False,
        ),
    ]
