# Generated by Django 4.2.1 on 2024-06-05 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('KnewITPeople', '0033_rename_description_company_email_and_more'),
        ('KnewITPeople', '0034_alter_person_company_employee'),
    ]

    operations = [
    ]
