# Generated by Django 4.2.1 on 2024-06-05 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('KnewITPeople', '0034_alter_company_website'),
        ('KnewITPeople', '0035_merge_20240605_1540'),
    ]

    operations = [
    ]
