# Generated by Django 4.2.1 on 2024-06-05 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KnewITPeople', '0036_merge_20240605_1544'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='facebook',
            field=models.TextField(blank=True, default=None),
        ),
        migrations.AddField(
            model_name='company',
            name='instagram',
            field=models.TextField(blank=True, default=None),
        ),
        migrations.AddField(
            model_name='company',
            name='youtube',
            field=models.TextField(blank=True, default=None),
        ),
    ]
