# Generated by Django 4.2.1 on 2024-06-05 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KnewITPeople', '0037_company_facebook_company_instagram_company_youtube'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='age',
            field=models.CharField(max_length=10),
        ),
    ]
