# Generated by Django 4.2.1 on 2024-06-05 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KnewITPeople', '0039_person_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='work_ex',
            field=models.TextField(blank=True, default='Без опыта', null=True),
        ),
    ]
