# Generated by Django 4.2.1 on 2024-06-06 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KnewITPeople', '0041_click_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
